# Symptom and disease data (mirrors app/api/chat/route.ts)

SYMPTOM_LIST = [
    "itching", "skin_rash", "nodal_skin_eruptions", "continuous_sneezing", "shivering",
    "chills", "joint_pain", "stomach_pain", "acidity", "ulcers_on_tongue",
    "muscle_wasting", "vomiting", "burning_micturition", "spotting_urination", "fatigue",
    "weight_gain", "anxiety", "cold_hands_and_feets", "mood_swings", "weight_loss",
    "restlessness", "lethargy", "patches_in_throat", "irregular_sugar_level", "cough",
    "high_fever", "sunken_eyes", "breathlessness", "sweating", "dehydration",
    "indigestion", "headache", "yellowish_skin", "dark_urine", "nausea",
    "loss_of_appetite", "pain_behind_the_eyes", "back_pain", "constipation", "abdominal_pain",
    "diarrhoea", "mild_fever", "yellow_urine", "yellowing_of_eyes", "acute_liver_failure",
    "fluid_overload", "swelling_of_stomach", "swelled_lymph_nodes", "malaise", "blurred_and_distorted_vision",
    "phlegm", "throat_irritation", "redness_of_eyes", "sinus_pressure", "runny_nose",
    "congestion", "chest_pain", "weakness_in_limbs", "fast_heart_rate", "pain_during_bowel_movements",
    "pain_in_anal_region", "bloody_stool", "irritation_in_anus", "neck_pain", "dizziness",
    "cramps", "bruising", "obesity", "swollen_legs", "swollen_blood_vessels",
    "puffy_face_and_eyes", "enlarged_thyroid", "brittle_nails", "swollen_extremeties", "excessive_hunger",
    "extra_marital_contacts", "drying_and_tingling_lips", "slurred_speech", "knee_pain", "hip_joint_pain",
    "muscle_weakness", "stiff_neck", "swelling_joints", "movement_stiffness", "spinning_movements",
    "loss_of_balance", "unsteadiness", "weakness_of_one_body_side", "loss_of_smell", "bladder_discomfort",
    "foul_smell_of_urine", "continuous_feel_of_urine", "passage_of_gases", "internal_itching", "toxic_look_(typhos)",
    "depression", "irritability", "muscle_pain", "altered_sensorium", "red_spots_over_body",
    "belly_pain", "abnormal_menstruation", "dischromic_patches", "watering_from_eyes", "increased_appetite",
    "polyuria", "family_history", "mucoid_sputum", "rusty_sputum", "lack_of_concentration",
    "visual_disturbances", "receiving_blood_transfusion", "receiving_unsterile_injections", "coma", "stomach_bleeding",
    "distention_of_abdomen", "history_of_alcohol_consumption", "fluid_overload.1", "blood_in_sputum", "prominent_veins_on_calf",
    "palpitations", "painful_walking", "pus_filled_pimples", "blackheads", "scurring",
    "skin_peeling", "silver_like_dusting", "small_dents_in_nails", "inflammatory_nails", "blister",
    "red_sore_around_nose", "yellow_crust_ooze",
]

DISEASE_SYMPTOM_MAP = {
    "itching": {"disease": "Fungal infection", "related_symptoms": ["skin_rash", "nodal_skin_eruptions", "dischromic_patches"]},
    "skin_rash": {"disease": "Fungal infection", "related_symptoms": ["itching", "nodal_skin_eruptions", "dischromic_patches"]},
    "nodal_skin_eruptions": {"disease": "Fungal infection", "related_symptoms": ["itching", "skin_rash", "dischromic_patches"]},
    "continuous_sneezing": {"disease": "Allergy", "related_symptoms": ["shivering", "chills", "watering_from_eyes"]},
    "shivering": {"disease": "Allergy", "related_symptoms": ["continuous_sneezing", "chills", "watering_from_eyes"]},
    "chills": {"disease": "Allergy", "related_symptoms": ["continuous_sneezing", "shivering", "watering_from_eyes"]},
    "joint_pain": {"disease": "Arthritis", "related_symptoms": ["muscle_weakness", "stiff_neck", "swelling_joints", "movement_stiffness", "painful_walking"]},
    "stomach_pain": {"disease": "GERD", "related_symptoms": ["acidity", "ulcers_on_tongue", "vomiting", "chest_pain", "cough"]},
    "acidity": {"disease": "GERD", "related_symptoms": ["stomach_pain", "ulcers_on_tongue", "vomiting", "chest_pain", "cough"]},
    "vomiting": {"disease": "Gastroenteritis", "related_symptoms": ["stomach_pain", "diarrhoea", "dehydration", "nausea", "headache"]},
    "fatigue": {"disease": "Chronic cholestasis", "related_symptoms": ["itching", "yellowish_skin", "nausea", "loss_of_appetite", "abdominal_pain", "dark_urine", "yellowing_of_eyes"]},
    "weight_loss": {"disease": "Diabetes", "related_symptoms": ["fatigue", "restlessness", "lethargy", "irregular_sugar_level", "blurred_and_distorted_vision", "obesity", "excessive_hunger", "increased_appetite", "polyuria"]},
    "cough": {"disease": "Bronchial Asthma", "related_symptoms": ["breathlessness", "fatigue", "high_fever", "mucoid_sputum", "phlegm", "chest_pain"]},
    "high_fever": {"disease": "Typhoid", "related_symptoms": ["chills", "vomiting", "headache", "nausea", "fatigue", "abdominal_pain", "diarrhoea", "constipation", "toxic_look_(typhos)", "belly_pain"]},
    "breathlessness": {"disease": "Bronchial Asthma", "related_symptoms": ["cough", "fatigue", "high_fever", "mucoid_sputum", "phlegm", "chest_pain"]},
    "headache": {"disease": "Migraine", "related_symptoms": ["acidity", "indigestion", "blurred_and_distorted_vision", "excessive_hunger", "stiff_neck", "depression", "irritability", "visual_disturbances"]},
    "nausea": {"disease": "Gastroenteritis", "related_symptoms": ["vomiting", "stomach_pain", "diarrhoea", "dehydration", "headache"]},
    "loss_of_appetite": {"disease": "Hepatitis B", "related_symptoms": ["itching", "fatigue", "lethargy", "yellowish_skin", "dark_urine", "nausea", "yellowing_of_eyes", "abdominal_pain", "malaise", "receiving_blood_transfusion", "receiving_unsterile_injections"]},
    "back_pain": {"disease": "Cervical spondylosis", "related_symptoms": ["neck_pain", "dizziness", "loss_of_balance", "weakness_in_limbs"]},
    "constipation": {"disease": "Drug Reaction", "related_symptoms": ["stomach_pain", "acidity", "vomiting", "abdominal_pain"]},
    "abdominal_pain": {"disease": "Peptic ulcer disease", "related_symptoms": ["vomiting", "loss_of_appetite", "abdominal_pain", "passage_of_gases", "internal_itching"]},
    "diarrhoea": {"disease": "Gastroenteritis", "related_symptoms": ["vomiting", "stomach_pain", "dehydration", "nausea", "headache"]},
    "mild_fever": {"disease": "Chicken pox", "related_symptoms": ["itching", "skin_rash", "fatigue", "lethargy", "high_fever", "headache", "loss_of_appetite", "mild_fever", "swelled_lymph_nodes", "malaise", "red_spots_over_body"]},
    "yellowish_skin": {"disease": "Jaundice", "related_symptoms": ["itching", "vomiting", "fatigue", "weight_loss", "high_fever", "dark_urine", "abdominal_pain", "yellowing_of_eyes"]},
    "dark_urine": {"disease": "Hepatitis D", "related_symptoms": ["joint_pain", "vomiting", "fatigue", "yellowish_skin", "nausea", "loss_of_appetite", "abdominal_pain", "yellowing_of_eyes"]},
    "chest_pain": {"disease": "Heart attack", "related_symptoms": ["vomiting", "breathlessness", "sweating"]},
    "dizziness": {"disease": "Hypertension", "related_symptoms": ["headache", "chest_pain", "lack_of_concentration"]},
    "neck_pain": {"disease": "Cervical spondylosis", "related_symptoms": ["back_pain", "dizziness", "loss_of_balance", "weakness_in_limbs"]},
    "swelling_joints": {"disease": "Osteoarthristis", "related_symptoms": ["joint_pain", "neck_pain", "knee_pain", "hip_joint_pain", "painful_walking"]},
    "muscle_pain": {"disease": "Dengue", "related_symptoms": ["skin_rash", "chills", "joint_pain", "vomiting", "fatigue", "high_fever", "headache", "nausea", "loss_of_appetite", "pain_behind_the_eyes", "back_pain", "malaise", "muscle_pain", "red_spots_over_body"]},
    "burning_micturition": {"disease": "Urinary tract infection", "related_symptoms": ["spotting_urination", "bladder_discomfort", "foul_smell_of_urine", "continuous_feel_of_urine"]},
    "spotting_urination": {"disease": "Urinary tract infection", "related_symptoms": ["burning_micturition", "bladder_discomfort", "foul_smell_of_urine", "continuous_feel_of_urine"]},
    "anxiety": {"disease": "Hyperthyroidism", "related_symptoms": ["fatigue", "mood_swings", "weight_loss", "restlessness", "sweating", "diarrhoea", "fast_heart_rate", "excessive_hunger", "muscle_weakness", "irritability", "abnormal_menstruation"]},
    "weight_gain": {"disease": "Hypothyroidism", "related_symptoms": ["fatigue", "cold_hands_and_feets", "mood_swings", "lethargy", "dizziness", "puffy_face_and_eyes", "enlarged_thyroid", "brittle_nails", "swollen_extremeties", "depression", "irritability", "abnormal_menstruation"]},
    "lethargy": {"disease": "Hepatitis A", "related_symptoms": ["joint_pain", "vomiting", "yellowish_skin", "dark_urine", "nausea", "loss_of_appetite", "abdominal_pain", "diarrhoea", "mild_fever", "yellowing_of_eyes", "muscle_pain"]},
    "skin_peeling": {"disease": "Psoriasis", "related_symptoms": ["skin_rash", "joint_pain", "silver_like_dusting", "small_dents_in_nails", "inflammatory_nails"]},
    "pus_filled_pimples": {"disease": "Acne", "related_symptoms": ["skin_rash", "blackheads", "scurring"]},
    "runny_nose": {"disease": "Common Cold", "related_symptoms": ["continuous_sneezing", "chills", "fatigue", "cough", "high_fever", "headache", "swelled_lymph_nodes", "malaise", "phlegm", "throat_irritation", "redness_of_eyes", "sinus_pressure", "runny_nose", "congestion", "chest_pain", "muscle_pain", "loss_of_smell"]},
    "congestion": {"disease": "Common Cold", "related_symptoms": ["continuous_sneezing", "chills", "fatigue", "cough", "high_fever", "headache", "swelled_lymph_nodes", "malaise", "phlegm", "throat_irritation", "redness_of_eyes", "sinus_pressure", "runny_nose", "congestion", "chest_pain", "muscle_pain", "loss_of_smell"]},
    "blister": {"disease": "Impetigo", "related_symptoms": ["skin_rash", "high_fever", "red_sore_around_nose", "yellow_crust_ooze"]},
    "red_sore_around_nose": {"disease": "Impetigo", "related_symptoms": ["skin_rash", "high_fever", "blister", "yellow_crust_ooze"]},
    "yellow_crust_ooze": {"disease": "Impetigo", "related_symptoms": ["skin_rash", "high_fever", "blister", "red_sore_around_nose"]},
    "depression": {"disease": "Hypothyroidism", "related_symptoms": ["fatigue", "weight_gain", "cold_hands_and_feets", "mood_swings", "lethargy", "dizziness", "puffy_face_and_eyes", "enlarged_thyroid", "brittle_nails", "swollen_extremeties", "irritability", "abnormal_menstruation"]},
    "muscle_weakness": {"disease": "Paralysis (brain hemorrhage)", "related_symptoms": ["vomiting", "headache", "weakness_of_one_body_side", "altered_sensorium"]},
    "dehydration": {"disease": "Gastroenteritis", "related_symptoms": ["vomiting", "stomach_pain", "diarrhoea", "nausea", "headache"]},
    "sweating": {"disease": "Malaria", "related_symptoms": ["chills", "vomiting", "high_fever", "headache", "nausea", "muscle_pain", "sweating"]},
    "phlegm": {"disease": "Pneumonia", "related_symptoms": ["chills", "fatigue", "cough", "high_fever", "breathlessness", "sweating", "malaise", "phlegm", "chest_pain", "fast_heart_rate", "rusty_sputum"]},
    "throat_irritation": {"disease": "Common Cold", "related_symptoms": ["continuous_sneezing", "cough", "high_fever", "headache", "phlegm", "runny_nose", "congestion", "sinus_pressure"]},
    "bloody_stool": {"disease": "Dimorphic hemmorhoids(piles)", "related_symptoms": ["constipation", "pain_during_bowel_movements", "pain_in_anal_region", "bloody_stool", "irritation_in_anus"]},
    "obesity": {"disease": "Diabetes", "related_symptoms": ["fatigue", "restlessness", "lethargy", "irregular_sugar_level", "blurred_and_distorted_vision", "weight_loss", "excessive_hunger", "increased_appetite", "polyuria"]},
    "knee_pain": {"disease": "Osteoarthristis", "related_symptoms": ["joint_pain", "neck_pain", "hip_joint_pain", "swelling_joints", "painful_walking"]},
    "hip_joint_pain": {"disease": "Osteoarthristis", "related_symptoms": ["joint_pain", "neck_pain", "knee_pain", "swelling_joints", "painful_walking"]},
    "swollen_legs": {"disease": "Varicose veins", "related_symptoms": ["fatigue", "cramps", "bruising", "obesity", "swollen_blood_vessels", "prominent_veins_on_calf"]},
    "red_spots_over_body": {"disease": "Chicken pox", "related_symptoms": ["itching", "skin_rash", "fatigue", "lethargy", "high_fever", "headache", "loss_of_appetite", "mild_fever", "swelled_lymph_nodes", "malaise"]},
    "painful_walking": {"disease": "Osteoarthristis", "related_symptoms": ["joint_pain", "neck_pain", "knee_pain", "hip_joint_pain", "swelling_joints"]},
    "palpitations": {"disease": "Heart attack", "related_symptoms": ["vomiting", "breathlessness", "sweating", "chest_pain"]},
    "fast_heart_rate": {"disease": "Hyperthyroidism", "related_symptoms": ["anxiety", "fatigue", "mood_swings", "weight_loss", "restlessness", "sweating", "diarrhoea", "excessive_hunger", "muscle_weakness", "irritability"]},
    "slurred_speech": {"disease": "Paralysis (brain hemorrhage)", "related_symptoms": ["vomiting", "headache", "muscle_weakness", "weakness_of_one_body_side", "altered_sensorium"]},
    "passage_of_gases": {"disease": "Peptic ulcer disease", "related_symptoms": ["vomiting", "loss_of_appetite", "abdominal_pain", "internal_itching"]},
}

DISEASE_DESCRIPTIONS = {
    "Fungal infection": "A fungal infection is a common skin condition caused by fungi. It often causes itching, rashes, and skin discoloration.",
    "Allergy": "An allergy occurs when the immune system reacts to a normally harmless substance. Common symptoms include sneezing, watery eyes, and rashes.",
    "GERD": "Gastroesophageal reflux disease (GERD) causes stomach acid to flow back into the esophagus, causing heartburn and chest discomfort.",
    "Chronic cholestasis": "A condition where the flow of bile from the liver is slowed or blocked, leading to itching, jaundice, and fatigue.",
    "Drug Reaction": "An adverse reaction to medication that can cause various symptoms including skin rash, fever, and organ damage.",
    "Peptic ulcer disease": "Open sores that develop on the inside lining of the stomach and small intestine, causing stomach pain.",
    "Gastroenteritis": "Inflammation of the stomach and intestines, typically resulting from a viral or bacterial infection.",
    "Diabetes": "A metabolic disease that causes high blood sugar. Symptoms include frequent urination, thirst, and hunger.",
    "Bronchial Asthma": "A condition where the airways narrow and swell and may produce extra mucus, making breathing difficult.",
    "Hypertension": "A condition where blood pressure against artery walls is consistently too high.",
    "Migraine": "A headache disorder characterized by recurrent headaches, often accompanied by nausea and sensitivity to light.",
    "Cervical spondylosis": "Age-related wear affecting the spinal disks in the neck, causing pain and stiffness.",
    "Jaundice": "A condition where the skin and whites of the eyes turn yellow due to high bilirubin levels.",
    "Malaria": "A disease caused by parasites transmitted through mosquito bites, causing fever, chills, and flu-like illness.",
    "Chicken pox": "A highly contagious viral infection causing an itchy, blister-like rash, fever, and tiredness.",
    "Dengue": "A mosquito-borne viral disease causing high fever, severe headache, and joint pain.",
    "Typhoid": "A bacterial infection from contaminated food or water causing high fever, weakness, and stomach pains.",
    "Hepatitis A": "A highly contagious liver infection caused by the hepatitis A virus.",
    "Hepatitis B": "A serious liver infection caused by the hepatitis B virus that can become chronic.",
    "Hepatitis C": "An infection caused by a virus that attacks the liver and leads to inflammation.",
    "Hepatitis D": "A serious liver disease caused by the hepatitis D virus, occurring only with hepatitis B.",
    "Hepatitis E": "A liver disease caused by the hepatitis E virus, usually spread through contaminated water.",
    "Arthritis": "Inflammation of one or more joints, causing pain and stiffness that can worsen with age.",
    "Heart attack": "A medical emergency where blood flow to the heart is blocked, causing chest pain and shortness of breath.",
    "Varicose veins": "Enlarged, swollen, and twisting veins, often appearing blue or dark purple on the legs.",
    "Hypothyroidism": "A condition where the thyroid gland doesn't produce enough thyroid hormones.",
    "Hyperthyroidism": "A condition where the thyroid gland produces too much thyroid hormone.",
    "Urinary tract infection": "An infection in any part of the urinary system, most commonly the bladder and urethra.",
    "Psoriasis": "A skin disease that causes red, itchy scaly patches, most commonly on the knees, elbows, trunk and scalp.",
    "Impetigo": "A highly contagious skin infection that mainly affects infants and young children, causing red sores.",
    "Common Cold": "A viral infection of the nose and throat (upper respiratory tract) causing runny nose, sneezing, and congestion.",
    "Pneumonia": "An infection that inflames the air sacs in one or both lungs, which may fill with fluid.",
    "Dimorphic hemmorhoids(piles)": "Swollen veins in the lower rectum and anus, causing discomfort and bleeding.",
    "Acne": "A skin condition that occurs when hair follicles become plugged with oil and dead skin cells.",
    "Osteoarthristis": "The most common form of arthritis, causing joint pain and reduced range of motion.",
    "Paralysis (brain hemorrhage)": "Loss of muscle function due to bleeding in the brain, requiring immediate medical attention.",
}

DISEASE_PRECAUTIONS = {
    "Fungal infection": ["bath twice", "use detol or neem in bathing water", "keep infected area dry", "use clean cloths"],
    "Allergy": ["apply calamine", "cover area with bandage", "use ice to compress itching", "consult nearest hospital"],
    "GERD": ["avoid fatty spicy food", "avoid lying down after eating", "maintain healthy weight", "exercise"],
    "Chronic cholestasis": ["cold baths", "anti itch medicine", "consult doctor", "eat healthy"],
    "Drug Reaction": ["stop irritation", "consult nearest hospital", "stop taking drug", "follow up"],
    "Peptic ulcer disease": ["avoid fatty spicy food", "consume probiotic food", "eliminate milk", "limit alcohol"],
    "Gastroenteritis": ["stop eating solid food for while", "try taking small sips of water", "rest", "ease back into eating"],
    "Diabetes": ["have balanced diet", "exercise", "consult doctor", "follow up"],
    "Bronchial Asthma": ["switch to loose cloothing", "take deep breaths", "get away from trigger", "seek help"],
    "Hypertension": ["meditation", "salt baths", "reduce stress", "get proper sleep"],
    "Migraine": ["meditation", "reduce stress", "use poloroid glasses in sun", "consult doctor"],
    "Cervical spondylosis": ["use heating pad or cold pack", "exercise", "take otc pain reliver", "consult doctor"],
    "Jaundice": ["drink plenty of water", "consume milk thistle", "eat fruits and high fiberous food", "medication"],
    "Malaria": ["consult nearest hospital", "avoid oily food", "avoid non veg food", "keep mosquitos out"],
    "Chicken pox": ["use neem in bathing", "consume neem leaves", "take vaccine", "avoid public places"],
    "Dengue": ["drink papaya leaf juice", "avoid fatty spicy food", "keep mosquitos away", "keep hydrated"],
    "Typhoid": ["eat high calorie vegitables", "antiboitic therapy", "consult doctor", "medication"],
    "Hepatitis A": ["consult nearest hospital", "wash hands through", "avoid fatty spicy food", "medication"],
    "Hepatitis B": ["consult nearest hospital", "vaccination", "eat healthy", "medication"],
    "Hepatitis C": ["consult nearest hospital", "vaccination", "eat healthy", "medication"],
    "Hepatitis D": ["consult doctor", "medication", "eat healthy", "follow up"],
    "Hepatitis E": ["stop alcohol consumption", "rest", "consult doctor", "medication"],
    "Arthritis": ["exercise", "use hot and cold therapy", "try acupuncture", "massage"],
    "Heart attack": ["call ambulance", "chew aspirin", "keep calm", "consult nearest hospital"],
    "Varicose veins": ["lie down flat and raise the leg high", "use ointments", "use vein compression", "dont stand still for long"],
    "Hypothyroidism": ["reduce stress", "exercise", "eat healthy", "get proper sleep"],
    "Hyperthyroidism": ["eat healthy", "massage", "use lemon balm", "take radioactive iodine treatment"],
    "Urinary tract infection": ["drink plenty of water", "increase vitamin c intake", "drink cranberry juice", "take probiotics"],
    "Psoriasis": ["wash hands with warm soapy water", "stop bleeding using pressure", "consult doctor", "salt baths"],
    "Impetigo": ["soak affected area in warm water", "use antibiotics", "remove scabs with wet compressed cloth", "consult doctor"],
    "Common Cold": ["drink vitamin c rich drinks", "take vapour", "avoid cold food", "keep fever in check"],
    "Pneumonia": ["consult doctor", "medication", "rest", "follow up"],
    "Dimorphic hemmorhoids(piles)": ["avoid fatty spicy food", "consume witch hazel", "warm bath with epsom salt", "consume alovera juice"],
    "Acne": ["bath twice", "avoid fatty spicy food", "drink plenty of water", "avoid too many products"],
    "Osteoarthristis": ["acetaminophen", "consult nearest hospital", "follow up", "salt baths"],
    "Paralysis (brain hemorrhage)": ["massage", "eat healthy", "exercise", "consult doctor"],
}

SYMPTOM_SEVERITY = {
    "itching": 1, "skin_rash": 3, "nodal_skin_eruptions": 4, "continuous_sneezing": 4, "shivering": 5,
    "chills": 3, "joint_pain": 3, "stomach_pain": 5, "acidity": 3, "ulcers_on_tongue": 4,
    "muscle_wasting": 3, "vomiting": 5, "burning_micturition": 6, "spotting_urination": 6, "fatigue": 4,
    "weight_gain": 3, "anxiety": 4, "cold_hands_and_feets": 5, "mood_swings": 3, "weight_loss": 3,
    "restlessness": 5, "lethargy": 2, "patches_in_throat": 6, "irregular_sugar_level": 5, "cough": 4,
    "high_fever": 7, "sunken_eyes": 3, "breathlessness": 4, "sweating": 3, "dehydration": 4,
    "indigestion": 5, "headache": 3, "yellowish_skin": 3, "dark_urine": 4, "nausea": 5,
    "loss_of_appetite": 4, "pain_behind_the_eyes": 4, "back_pain": 3, "constipation": 4, "abdominal_pain": 4,
    "diarrhoea": 6, "mild_fever": 5, "yellow_urine": 4, "yellowing_of_eyes": 4, "acute_liver_failure": 6,
    "fluid_overload": 6, "swelling_of_stomach": 7, "swelled_lymph_nodes": 6, "malaise": 6,
    "blurred_and_distorted_vision": 5, "phlegm": 5, "throat_irritation": 4, "redness_of_eyes": 4,
    "sinus_pressure": 4, "runny_nose": 5, "congestion": 5, "chest_pain": 7, "weakness_in_limbs": 7,
    "fast_heart_rate": 5, "pain_during_bowel_movements": 5, "pain_in_anal_region": 6, "bloody_stool": 5,
    "irritation_in_anus": 6, "neck_pain": 5, "dizziness": 4, "cramps": 4, "bruising": 4,
    "obesity": 4, "swollen_legs": 5, "swollen_blood_vessels": 5, "puffy_face_and_eyes": 5,
    "enlarged_thyroid": 6, "brittle_nails": 5, "swollen_extremeties": 5, "excessive_hunger": 4,
    "extra_marital_contacts": 5, "drying_and_tingling_lips": 4, "slurred_speech": 4, "knee_pain": 3,
    "hip_joint_pain": 2, "muscle_weakness": 2, "stiff_neck": 5, "swelling_joints": 5,
    "movement_stiffness": 5, "spinning_movements": 6, "loss_of_balance": 4, "unsteadiness": 4,
    "weakness_of_one_body_side": 4, "loss_of_smell": 3, "bladder_discomfort": 4,
    "foul_smell_of_urine": 5, "continuous_feel_of_urine": 6, "passage_of_gases": 5,
    "internal_itching": 4, "toxic_look_(typhos)": 5, "depression": 3, "irritability": 2,
    "muscle_pain": 2, "altered_sensorium": 2, "red_spots_over_body": 4, "belly_pain": 4,
    "abnormal_menstruation": 6, "dischromic_patches": 6, "watering_from_eyes": 4,
    "increased_appetite": 5, "polyuria": 4, "family_history": 5, "mucoid_sputum": 4,
    "rusty_sputum": 4, "lack_of_concentration": 3, "visual_disturbances": 2,
    "receiving_blood_transfusion": 5, "receiving_unsterile_injections": 5, "coma": 7,
    "stomach_bleeding": 6, "distention_of_abdomen": 4, "history_of_alcohol_consumption": 5,
    "blood_in_sputum": 5, "prominent_veins_on_calf": 6, "palpitations": 4,
    "painful_walking": 2, "pus_filled_pimples": 2, "blackheads": 2, "scurring": 2,
    "skin_peeling": 3, "silver_like_dusting": 2, "small_dents_in_nails": 2,
    "inflammatory_nails": 2, "blister": 4, "red_sore_around_nose": 2, "yellow_crust_ooze": 3,
}
